#//=============================================\\
#||                                            ||
#||                PremiumProxy                ||
#||                    0.4                     ||
#||                                            ||
#\\============================================//
#
#When using the plugin, be sure to use plugins that
#allow licensed players to switch to online mode.
#
#При использовании плагина обязательно используйте плагины, которые
#позволяют игрокам с лицензией перейти в online-mode.
#
#Spigot: TIplur

#+-------------------------------------------------+
#Plugin Messages
#Сообщения плагина
Messages:
  #Prefix plugin
  #Префикс плагина
  Prefix: "&a[&6PremiumProxy&a]"
  #Message format (true - JSON text | false - default text)
  #Формат сообщений (true - JSON текст | false - обычный текст)
  Format-Text: true
  #Default text message
  #Обычный текст сообщения
  NotPremium-TEXT: "Login Error: Invalid session (&cSwitch to &nlicense mode&r&f)"
  #JSON text message
  #JSON текст сообщения
  NotPremium-JSON:
    #Message
    #Сообщение
    Text: "Login Error: Invalid session (&cSwitch to &nlicense mode&r&f)"
    #Message Hover
    #Сообщение, которое отображается при наведении.
    Hover: "\n&eIf you have a license, please click to confirm.\nIf you have a pirate client, you will not be able to log in to this server.\n"
    #Executed command when clicked
    #Команда которая выполняется при клике.
    Command: "/premium"
  #Title text message
  Title:
    #Enable/Disable title
    #Включение/Выключение сообщения на экране
    Enable: true
    #Title text
    #Заголовок сообщения на экране
    Title: "Login Error: Invalid session"
    #SubTitle text
    #Подзаголовок сообщения на экране
    SubTitle: "(&cSwitch to &nlicense mode&r&f)"
  #ActionBar text message
  ActionBar:
    #Enable/Disable actionbar
    #Включение/Выключение сообщения над панелью инвентаря
    Enable: true
    #ActionBar text
    #Текст сообщения над панелью инвентаря
    Text: "Login Error: Invalid session (&cSwitch to &nlicense mode&r&f)"
#+-------------------------------------------------+

#+-------------------------------------------------+
Servers:
  #Servers that will be checked for a license when logging in.
  #Specify server names from the BungeeCord configuration.
  #Серверы, которые будут проверены на наличие лицензии при входе на сервер.
  #Укажите имена серверов из конфигурации BungeeCord.
  Protect-Premium:
    - server
    - server2
#+-------------------------------------------------+